=== robedjason/portfolio/public/static/data/schemas/tech.schema.json
{
  "$ref": "#/definitions/Tech",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Tech": {
      "additionalProperties": false,
      "properties": {
        "categoryKey": {
          "enum": [
            "BE",
            "FE",
            "DB",
            "INFRA"
          ],
          "type": "string"
        },
        "experienceLevel": {
          "enum": [
            "HIGH",
            "MEDIUM",
            "LOW"
          ],
          "type": "string"
        },
        "iconName": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "yearsExperience": {
          "type": "number"
        }
      },
      "required": [
        "key",
        "title",
        "iconName",
        "experienceLevel",
        "yearsExperience",
        "categoryKey"
      ],
      "type": "object"
    }
  }
}

=== robedjason/portfolio/public/static/data/techs.json
[
    {
        "key": "JAVA",
        "title": "Java",
        "iconName": "java.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "BE"
    },
    {
        "key": "KOTLIN",
        "title": "Kotlin",
        "iconName": "kotlin.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "BE"
    },
    {
        "key": "POSTGRESQL",
        "title": "PostgreSQL",
        "iconName": "postgresql.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "DB"
    },
    {
        "key": "REACT-JS",
        "title": "ReactJS",
        "iconName": "react.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "FE"
    },
    {
        "key": "DOCKER",
        "title": "Docker",
        "iconName": "docker.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "INFRA"
    },
    {
        "key": "JAVASCRIPT",
        "title": "JavaScript",
        "iconName": "javascript.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "FE"
    },
    {
        "key": "SPRING",
        "title": "Spring",
        "iconName": "springboot.svg",
        "yearsExperience": 5,
        "experienceLevel": "HIGH",
        "categoryKey": "BE"
    },
    {
        "key": "PYTHON",
        "title": "Python",
        "iconName": "python.svg",
        "yearsExperience": 4,
        "experienceLevel": "MEDIUM",
        "categoryKey": "BE"
    },
    {
        "key": "TYPESCRIPT",
        "title": "TypeScript",
        "iconName": "typescript.svg",
        "yearsExperience": 3,
        "experienceLevel": "MEDIUM",
        "categoryKey": "FE"
    },
    {
        "key": "MYSQL",
        "title": "MySQL",
        "iconName": "mysql.svg",
        "yearsExperience": 3,
        "experienceLevel": "MEDIUM",
        "categoryKey": "DB"
    },
    {
        "key": "KUBERNETES",
        "title": "Kubernetes",
        "iconName": "kubernetes.svg",
        "yearsExperience": 3,
        "experienceLevel": "MEDIUM",
        "categoryKey": "INFRA"
    },
    {
        "key": "DJANGO",
        "title": "Django",
        "iconName": "django.svg",
        "yearsExperience": 1,
        "experienceLevel": "LOW",
        "categoryKey": "BE"
    },
    {
        "key": "REACT-NATIVE",
        "title": "React Native",
        "iconName": "react.svg",
        "yearsExperience": 1,
        "experienceLevel": "LOW",
        "categoryKey": "FE"
    },
    {
        "key": "SQLITE",
        "title": "SQLite",
        "iconName": "sqlite.svg",
        "yearsExperience": 1,
        "experienceLevel": "LOW",
        "categoryKey": "DB"
    }
]
